export const SITE_BASE_PATH = process.env.NEXT_PUBLIC_BASE_PATH || ""
export const SITE_URL = "https://www.tgpugulf.com"
export const COMPANY_NAME = "TGPU Gulf Advisory"
export const COMPANY_PHONE = "+60 12-868 1339"
export const COMPANY_PHONE_E164 = "+60128681339"
export const COMPANY_EMAIL = "mamduh@tgpugulf.com"
export const COMPANY_LOCATION = "Kuala Lumpur, Malaysia"
export const COMPANY_REGISTRATION = "CA0427558-D"
